# /etc/dovecot/conf.d/10-mail.conf – DMF Mail

# Maildir format in /var/mail/vhosts/<domain>/<user>/
mail_home    = /var/mail/vhosts/%d/%n
mail_location = maildir:~/Maildir

# Run as vmail user (uid/gid 5000)
mail_uid = 5000
mail_gid = 5000

# Namespace
namespace inbox {
  inbox = yes
  separator = /
  mailbox Drafts {
    special_use = \Drafts
    auto = subscribe
  }
  mailbox Junk {
    special_use = \Junk
    auto = subscribe
  }
  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }
}
